<main>
	
	<div class="wrapper">
	
		<section class="primary left">
			<?php print render($page['content']); ?>
		</section>

	  <aside class="secondary right">
	  	<div class="widget fade-in">
	  		<h2 class="title">Sign up for the cause!</h2>
	  		<div class="content">
		  		<p>Be a human sponsor to a space cat residing in your neighborhood.</p>
		  		<p><em>Click below to sign up:</em></p>
		  		<a href="#" class="btn wobble">Sign Up!</a>
		  	</div>
	  	</div>
	  </aside>

	</div>

</main>